variables:
  system.debug: true
stages:
- stage: Dev
  variables:
    system.debug: true
  jobs:
  - job: DevJob
    displayName: Dev
    continueOnError: true
    pool:
      vmImage: 'ubuntu-16.04'
      demand: maven
    steps:
    - task: Maven@3
      displayName: 'Build Lite: Maven pom.xml(lite)'
      inputs:
        mavenPomFile: 'pom-lite.xml'
    #- task: Maven@3
    #  displayName: 'Build Full: Maven pom.xml(full)'
    #  inputs:
    #    mavenPomFile: 'pom-full.xml'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/target'
        Contents: '*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
    #- script: |
    #    echo "running tests..."
    #    echo 'Tests complete.'
    #    echo $(build.artifactstagingdirectory)

    - task: GithubRelease@0
      displayName: 'Discard GitHub Release'
      inputs:
        githubConnection: zenithworks
        repositoryName: zenithworks/javaMavenApp
        action: Discard
        tag: 'draftVersion-2.1'

